### PR TITLE
Fix for using with CloudBees Folder plugin

### PR DESCRIPTION
**Pull request by Brantone**
https://issues.jenkins-ci.org/browse/JENKINS-24396

### CODE REVIEW

**Comment by Brantone** [comment]
Is anyone maintaining this plugin any more??

**Comment by ctapobep** [comment]
I don't think so. Might make sense to take over the ownership and maintain the plugin on your own. And don't forget about thorough testing :)

**Comment by Brantone** [comment]
Looks like @ndeloof was the last to merge anything ... any insight?

**Comment by Brantone** [comment]
Heh, that was awesome and fast, thank you kindly.
Are there still plans for maintenance and up-keep, or need a 2nd set of hands to help out? Hit me up on e-mail, can discuss further there.
In mean-time ... thanks again!! :)

**Comment by ndeloof** [comment]
I can't see active maintenance on this plugin, so feel free to request ownership on jenkins-dev ML

**Comment by Brantone** [comment]
Cheers.

**Pull request merged**
